# Generated by Django 3.1.1 on 2021-07-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesion',
            old_name='quesion_Text',
            new_name='quesion_text',
        ),
    ]
