# Generated by Django 3.1.1 on 2021-07-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210722_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quesion',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quesion_text',
            new_name='question_text',
        ),
    ]
